import Markdown from 'markdown-to-jsx';
import { useMemo } from 'react';

// Light wrapper around markdown-to-jsx. Renders a document with an
// autogenerated table-of-contents sidebar built from `##` headings.
export function MarkdownPage({ source }: { source: string }) {
  const toc = useMemo(() => extractToc(source), [source]);

  return (
    <div className="doc">
      {toc.length > 0 ? (
        <nav className="doc__toc" aria-label="Table of contents">
          <h2 className="doc__toc-title">On this page</h2>
          <ul>
            {toc.map(({ id, text }) => (
              <li key={id}>
                <a href={`#${id}`}>{text}</a>
              </li>
            ))}
          </ul>
        </nav>
      ) : null}
      <main className="doc__content">
        <Markdown
          options={{
            overrides: {
              h2: { component: AnchoredHeading('h2') },
              h3: { component: AnchoredHeading('h3') },
              a: {
                props: {
                  rel: 'noreferrer',
                },
              },
            },
          }}
        >
          {source}
        </Markdown>
      </main>
    </div>
  );
}

function extractToc(source: string): Array<{ id: string; text: string }> {
  const out: Array<{ id: string; text: string }> = [];
  const lines = source.split('\n');
  let inFence = false;
  for (const line of lines) {
    if (line.startsWith('```')) inFence = !inFence;
    if (inFence) continue;
    const m = /^##\s+(.+?)\s*$/.exec(line);
    if (!m) continue;
    const text = m[1]!.replace(/[`*_]/g, '');
    out.push({ id: slug(text), text });
  }
  return out;
}

function slug(s: string): string {
  return s
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, '')
    .trim()
    .replace(/\s+/g, '-');
}

function AnchoredHeading(Tag: 'h2' | 'h3') {
  return function Heading({ children }: { children?: React.ReactNode }) {
    const id = slug(childrenToText(children));
    return <Tag id={id}>{children}</Tag>;
  };
}

function childrenToText(node: React.ReactNode): string {
  if (typeof node === 'string') return node;
  if (typeof node === 'number') return String(node);
  if (Array.isArray(node)) return node.map(childrenToText).join('');
  if (node && typeof node === 'object' && 'props' in node) {
    const props = (node as { props?: { children?: React.ReactNode } }).props;
    return childrenToText(props?.children);
  }
  return '';
}
